document:
  title: "Create react-app"
  organization: ""
projects:
  - id: "Gradle:com.philips.research.spdxbuilder:spdx-builder:v0.5.0"
    excluded:
      - "annotation*"
      - "archives"
      - "runtime*"
      - "test*"
curations:
  - purl: "pkg:maven/philips/spdx-builder@v0.5.0"
    license: "MIT"
