document:
  title: "Create react-app"
  organization: ""
projects:
  - id: "Yarn::test-spdx-action:0.1.0"
    excluded:
      - "annotation*"
      - "archives"
      - "runtime*"
      - "test*"
curations:
  - purl: "Yarn::test-spdx-action:0.1.0"
    license: "MIT"
