name: Get licenses

on:
  push:
  workflow_dispatch:

jobs:
  scanLicenses:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create spdx-file tree-based-input
      id: spdx-builder-tree
      uses: philips-software/spdx-action@main
      with:
        project: my-project
        mode: 'tree'
        tree: 'create-react-app-dependencies.txt'
        format: 'npm'

    - name: ls
      run: ls -alh
      
    - uses: actions/upload-artifact@v2
      with:
        name: licenses-tree
        path: ${{ steps.spdx-builder-tree.outputs.spdx-file }}

  generate-provenance:
    needs: scanLicenses
    name: Generate build provenance
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2

      - name: Generate provenance
        uses: slsa-framework/github-actions-demo@v0.1
        with:
          artifact_path: license-tree/

      - name: Upload provenance
        uses: actions/upload-artifact@v2
        with:
          path: build.provenance
