name: Get licenses

on:
  push:

jobs:
  scanLicenses:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.1'
    - name: Create spdx-file ort version bring-your-own-ort
      id: spdx-builder-2020-10-12
      uses: philips-software/spdx-action@bring-your-own-ort
      with:
        project: my-project
        ort-file: test.json
    - uses: actions/upload-artifact@v2
      with:
        name: licenses-2020-10-12
        path: ${{ steps.spdx-builder-2020-10-12.outputs.spdx-file }}
