name: Get licenses

on:
  push:
  workflow_dispatch:

jobs:
  scanLicenses:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set dependency tree
      id: dependencies
      run: |
        dependencies="$(cat create-react-app-dependencies.txt)"
        echo "::set-output name=DEPENDENCIES::$dependencies"

    - name: Create spdx-file tree-based-input
      id: spdx-builder-tree
      uses: philips-software/spdx-action@tree-based-input
      with:
        project: my-project
        mode: 'tree'
        tree: "${{ steps.dependencies.outputs.DEPENDENCIES }}"
        format: 'npm'

    - uses: actions/upload-artifact@v2
      with:
        name: licenses-tree
        path: ${{ steps.spdx-builder-tree.outputs.spdx-file }}
